source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "webrick", "~> 1.8"
gem "csv" # Required for Ruby 3.4+
gem "bigdecimal" # Required for Ruby 3.4+
